package com.newoether.agora.model

import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import org.junit.Assert.assertEquals
import org.junit.Assert.assertTrue
import org.junit.Test

class AgentTest {

    private val json = Json { ignoreUnknownKeys = true }

    @Test
    fun `agent round-trips through json`() {
        val agent = Agent(
            name = "代码评审",
            rolePrompt = "你是资深代码评审专家，专注可维护性与安全。",
            providerKey = "OpenAI:gpt-4o",
            enabled = true,
        )
        val encoded = json.encodeToString(agent)
        val decoded = json.decodeFromString<Agent>(encoded)
        assertEquals(agent, decoded)
    }

    @Test
    fun `agent fields survive decode`() {
        val agent = Agent(name = "A", rolePrompt = "role", providerKey = "Provider:model")
        val decoded = json.decodeFromString<Agent>(json.encodeToString(agent))
        assertEquals("A", decoded.name)
        assertEquals("role", decoded.rolePrompt)
        assertEquals("Provider:model", decoded.providerKey)
    }

    @Test
    fun `agent defaults are stable`() {
        val agent = Agent(name = "X", rolePrompt = "y", providerKey = "Z")
        assertTrue(agent.enabled)
        // UUID id (36 chars) is generated by default.
        assertEquals(36, agent.id.length)
    }

    @Test
    fun `missing id decodes with a fresh id`() {
        // Legacy/malformed payload without an id must still decode (default applied).
        val encoded = """{"name":"无id","rolePrompt":"r","providerKey":"P:m"}"""
        val decoded = json.decodeFromString<Agent>(encoded)
        assertEquals(36, decoded.id.length)
    }
}
